apiVersion: v1
kind: ConfigMap
metadata:
  name: team-finder-config
  namespace: team-finder
data:
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  POSTGRES_DB: "team_finder"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  TASK_VERSION: "3"
