apiVersion: v1
kind: Secret
metadata:
  name: team-finder-secret
  namespace: team-finder
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "fkwjeqwrdl"
  POSTGRES_USER: "team_finder"
  POSTGRES_PASSWORD: "team_finder"
