apiVersion: v1
kind: Secret
metadata:
  name: team-finder-secret
  namespace: team-finder
type: Opaque
data:
  DJANGO_SECRET_KEY: "Zmt3amVxd3JkbA=="
  POSTGRES_USER: "dGVhbV9maW5kZXI="
  POSTGRES_PASSWORD: "dGVhbV9maW5kZXI="
